device:
  ID: "KitchenAgent"
  Type: "Lights and AC"
  BeaconRate: 20
  nSensors: 2
  nActuators: 2

sensors:
  - ID: "KitchenLuminositySensor"
    Type: "Luminosity"
    Status: 80
    MinValue: 0
    MaxValue: 100
    Virtual:
      GradientChange: false
      Factor: 20
      ActuatorGetInfo:
        Object: 3
        Index: 1

      
  - ID: "KitchenTemperatureSensor"
    Type: "Temperature"
    Status: 25
    MinValue: -10
    MaxValue: 50
    Virtual:
      GradientChange: true
      Factor: 1
      ActuatorGetInfo:
        Object: 3
        Index: 2

actuators:
  - ID: "KitchenLightActuator"
    Type: "Light"
    Status: 1
    MinValue: 0
    MaxValue: 5
  - ID: "KitchenACActuator"
    Type: "AC"
    Status: 20
    MinValue: 0
    MaxValue: 60